name: hello-world
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm run build 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm test -- --watch=false --browsers=ChromeHeadless
      
    
