name: hello-world
on: push
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout repository code
        uses: actions/checkout@v3
      - run: echo "HELLO WORLD"
      - name: use node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'
      - run: npm install
      - run: npm run build
      - run: npm run test
